# Generated by Django 6.0.3 on 2026-03-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parent",
            old_name="father_occuoation",
            new_name="father_occupation",
        ),
        migrations.RenameField(
            model_name="parent",
            old_name="mother_occuoation",
            new_name="mother_occupation",
        ),
    ]
