# Generated by Django 6.0.3 on 2026-04-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_father_occuoation_parent_father_occupation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="father_email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
