# Generated by Django 6.0.3 on 2026-04-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_parent_father_email_alter_student_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_image",
        ),
    ]
