# Generated by Django 6.0.3 on 2026-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_remove_student_student_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_image",
            field=models.ImageField(blank=True, upload_to="student/"),
        ),
    ]
