# Generated by Django 6.0.3 on 2026-04-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_name", models.CharField(max_length=150)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("event_date", models.DateField()),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
            ],
        ),
    ]
