# Generated by Django 6.0.3 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_id', models.CharField(max_length=100)),
                ('fees_type', models.CharField(choices=[('monthly fees', 'Monthly Fees'), ('admission Fees', 'Admission Fees'), ('class test', 'Class Test'), ('exam fees', 'Exam Fees'), ('hostel fees', 'Hostel Fees'), ('other', 'Other')], max_length=50)),
                ('student_class', models.CharField(max_length=100)),
                ('fees_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
