# Generated by Django 6.0.3 on 2026-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="WWy2tSrYHvYYBEE4fBpeN3AmQ2uy318y",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
