# Generated by Django 6.0.3 on 2026-04-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0002_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="ALjf1oF3fRcJwWEQUZABrE4nj2mKpuUu", max_length=32, unique=True
            ),
        ),
    ]
