# Generated by Django 6.0.3 on 2026-04-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="Ce3LWejv4zC2O6tfeqby7r7D8XpuENS7", max_length=32, unique=True
            ),
        ),
    ]
