# Generated by Django 6.0.3 on 2026-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0004_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="qNV7BACKRbwXEIZ0THJVE7atz4yv0c6m", max_length=32, unique=True
            ),
        ),
    ]
