# Generated by Django 6.0.3 on 2026-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0005_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="YCS6PIkizMEAgif0Wol9bHvRzEbgw7P8", max_length=32, unique=True
            ),
        ),
    ]
