# Generated by Django 6.0.3 on 2026-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0008_customuser_login_token_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="U4bJFMbG5q1ankMnJMIV7R1xmAUlk3sO",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
