# Generated by Django 6.0.3 on 2026-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0010_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="57LRDNvAftLmweP958lvaEbmRSKKC6JJ",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
