# Generated by Django 6.0.3 on 2026-04-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0011_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="2WnXZLtWnyY0SmPQoYQOi8eEab3ZarAB",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
