# Generated by Django 6.0.3 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='og9kRmZZTCfXzFeTLu8Ak1gvujHSBAC5', editable=False, max_length=32, unique=True),
        ),
    ]
