# Generated by Django 6.0.3 on 2026-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0019_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="MAvMyDQ4euygrw3ZJh9jTeJqRbVdDAJL",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
