# Generated by Django 6.0.3 on 2026-04-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0022_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="Q9GKj6VBj2ezAepxEOx2xjSpK4GEKzr1",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
