# Generated by Django 6.0.3 on 2026-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0024_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="OlUzBVEPBjgBk2l3wtraaxjTN5xaa45w",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
