# Generated by Django 6.0.3 on 2026-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "home_auth",
            "0025_alter_customuser_email_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="IE9d6N9o1N5jBecwQTSa3YWKH1sFYrM0",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
