# Generated by Django 6.0.3 on 2026-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0027_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="tmX6EqcFxYhfIWsOgkfMj4uQm0Tz2iRi",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
