# Generated by Django 6.0.3 on 2026-04-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0002_rename_father_occuoation_parent_father_occupation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeesCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fees_type",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition"),
                            ("exam", "Exam"),
                            ("admission", "Admission"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fees_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
        ),
    ]
